<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Admin extends MY_Controller {
 public function transfers(){$rows=$this->db->select('transactions.*,users.first_name,users.last_name,users.email')->from('transactions')->join('accounts','accounts.id=transactions.account_id')->join('users','users.id=accounts.user_id')->where('transactions.type','transfer')->order_by('transactions.id','DESC')->get()->result_array();$this->admin_view('admin/table',array('title'=>'Manage transfer requests','rows'=>$rows,'type'=>'transfers'));}
 private function audit($action,$resource,$id){$manager=$this->session->userdata('user');$this->db->insert('audit_logs',array('manager_id'=>$manager['id'],'action'=>$action,'resource_type'=>$resource,'resource_id'=>(int)$id,'created_at'=>date('Y-m-d H:i:s')));}
 private function admin_view($content,$data=array()){ $this->require_login('manager');$this->view($content,$data,'admin'); }
 public function login(){if($this->input->method()==='post'){$user=$this->User_model->find_by_email($this->input->post('email',TRUE));if($user && $user['role']==='manager' && password_verify($this->input->post('password'),$user['password_hash'])){$this->session->regenerate_id(TRUE);$this->session->set_userdata('user',array('id'=>$user['id'],'name'=>$user['first_name'].' '.$user['last_name'],'role'=>'manager'));redirect('admin');}$data['error']='Invalid manager credentials.';}$this->view('auth/admin_login',isset($data)?$data:array(),'auth');}
 public function logout(){$this->session->sess_destroy();redirect('admin/login');}
 public function index(){$this->admin_view('admin/dashboard',array('title'=>'Dashboard','customers'=>$this->User_model->count_role('customer'),'pending_kyc'=>$this->Account_model->admin_count('kyc_applications','pending'),'pending_loans'=>$this->Account_model->admin_count('loans','pending'),'pending_cards'=>$this->Account_model->admin_count('cards','pending')));}
 public function users(){$this->admin_view('admin/users',array('title'=>'Manage users','users'=>$this->User_model->all_customers()));}
 public function create_user(){if($this->input->method()==='post'){$this->User_model->create(array('role'=>'customer','first_name'=>$this->input->post('first_name',TRUE),'last_name'=>$this->input->post('last_name',TRUE),'email'=>$this->input->post('email',TRUE),'password'=>$this->input->post('password'),'phone'=>$this->input->post('phone',TRUE),'country'=>$this->input->post('country',TRUE),'status'=>'active'));$this->session->set_flashdata('success','Customer created.');redirect('admin/users');}$this->admin_view('admin/create_user',array('title'=>'Create a new user'));}
 public function kyc(){$this->admin_view('admin/table',array('title'=>'Grand Chase KYC application list','rows'=>$this->Account_model->list_with_user('kyc_applications'),'type'=>'kyc'));}
 public function deposits(){$rows=$this->db->select('transactions.*,users.first_name,users.last_name,users.email')->from('transactions')->join('accounts','accounts.id=transactions.account_id')->join('users','users.id=accounts.user_id')->where('transactions.type','deposit')->order_by('transactions.id','DESC')->get()->result_array();$this->admin_view('admin/table',array('title'=>'Manage clients deposits','rows'=>$rows,'type'=>'deposits'));}
 public function loans(){$this->admin_view('admin/table',array('title'=>'Requested loans','rows'=>$this->Account_model->list_with_user('loans'),'type'=>'loans'));}
 public function cards(){$this->admin_view('admin/table',array('title'=>'Manage virtual cards','rows'=>$this->Account_model->list_with_user('cards'),'type'=>'cards'));}
 public function card_applications(){$this->admin_view('admin/table',array('title'=>'Pending card applications','rows'=>$this->Account_model->list_with_user('cards'),'type'=>'card-applications'));}
 public function create_manager(){if($this->input->method()==='post'){$this->form_validation->set_rules('email','Email','required|valid_email|is_unique[users.email]');$this->form_validation->set_rules('password','Password','required|min_length[12]');if($this->form_validation->run()){$this->User_model->create(array('role'=>'manager','first_name'=>$this->input->post('first_name',TRUE),'last_name'=>$this->input->post('last_name',TRUE),'email'=>$this->input->post('email',TRUE),'password'=>$this->input->post('password'),'status'=>'active'));$this->session->set_flashdata('success','Manager created.');redirect('admin/managers');}}$this->admin_view('admin/create_manager',array('title'=>'Create manager'));}
 public function update_user_status($id,$status){$this->require_login('manager');if(!in_array($status,array('active','suspended'),TRUE))show_404();$this->db->where(array('id'=>(int)$id,'role'=>'customer'))->update('users',array('status'=>$status,'updated_at'=>date('Y-m-d H:i:s')));$this->audit($status,'user',$id);$this->session->set_flashdata('success','Customer access updated.');redirect('admin/users');}
 public function update_status($resource,$id,$status){$allowed=array('kyc'=>'kyc_applications','loans'=>'loans','cards'=>'cards','card-applications'=>'cards','transfers'=>'transactions');if(!isset($allowed[$resource]) || !in_array($status,array('approved','rejected','active','blocked'),TRUE))show_404();$this->require_login('manager');if($allowed[$resource]==='cards' && $status==='active'){$this->db->where('id',(int)$id)->update('cards',array('status'=>'active','last_four'=>str_pad((string)random_int(0,9999),4,'0',STR_PAD_LEFT)));}elseif($resource==='transfers'){$transfer=$this->db->get_where('transactions',array('id'=>(int)$id,'status'=>'pending'))->row_array();if($transfer && $status==='approved'){$this->db->trans_start();$this->db->set('balance','balance - '.(float)$transfer['amount'],FALSE)->where('id',$transfer['account_id'])->where('balance >=',(float)$transfer['amount'])->update('accounts');if($this->db->affected_rows()===1)$this->db->where('id',$transfer['id'])->update('transactions',array('status'=>'completed'));else $this->db->where('id',$transfer['id'])->update('transactions',array('status'=>'rejected'));$this->db->trans_complete();}elseif($transfer){$this->db->where('id',$transfer['id'])->update('transactions',array('status'=>'rejected'));}}else{$this->db->where(array('id'=>(int)$id,'status'=>'pending'))->update($allowed[$resource],array('status'=>$status));}$this->audit($status,$resource,$id);$this->session->set_flashdata('success','Record status updated.');redirect('admin/'.$resource);}
 public function managers(){$this->admin_view('admin/managers',array('title'=>'Managers list','managers'=>$this->db->select('first_name,last_name,email,status,created_at')->get_where('users',array('role'=>'manager'))->result_array()));}
}
