<?php defined('BASEPATH') OR exit('No direct script access allowed');
$config['base_url'] = getenv('APP_URL') ?: 'http://localhost:8000/';
$config['index_page'] = '';
$config['uri_protocol'] = 'REQUEST_URI';
$config['url_suffix'] = '';
$config['language'] = 'english';
$config['charset'] = 'UTF-8';
$config['enable_hooks'] = FALSE;
$config['subclass_prefix'] = 'MY_';
$config['composer_autoload'] = FALSE;
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';
$config['enable_query_strings'] = FALSE;
$config['allow_get_array'] = TRUE;
$config['log_threshold'] = 1;
$config['encryption_key'] = getenv('APP_KEY') ?: 'change-this-32-character-key-before-production';
$config['sess_driver'] = 'files'; $config['sess_cookie_name'] = 'grand_chase_session'; $config['sess_expiration'] = 7200; $config['sess_save_path'] = APPPATH.'cache/sessions'; $config['sess_match_ip'] = FALSE; $config['sess_time_to_update'] = 300; $config['sess_regenerate_destroy'] = FALSE;
$config['cookie_prefix']=''; $config['cookie_domain']=''; $config['cookie_path']='/'; $config['cookie_secure']=FALSE; $config['cookie_httponly']=TRUE;
$config['csrf_protection'] = TRUE; $config['csrf_token_name'] = 'csrf_token'; $config['csrf_cookie_name'] = 'csrf_cookie'; $config['csrf_expire'] = 7200;
$config['global_xss_filtering'] = FALSE; $config['compress_output']=FALSE; $config['time_reference']='local'; $config['rewrite_short_tags']=FALSE; $config['proxy_ips']='';
